spring:
  security:
    user:
      password: 123456
      name: user
  application:
    name: base-oauth2
server:
  port: 7779
#服务注册
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:9443/eureka  #注册 中心已经开启认证
