server:
  port: 8030
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: base-connector
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:7990
management:
  endpoints:
    web:
      exposure:
        include: \*
feign:
  hystrix:
    enabled: true