server:
  port: 8030
spring:
  profiles:
    active: @package.environment@
  main:
    allow-bean-definition-overriding: true
  application:
    name: base-connector
management:
  endpoints:
    web:
      exposure:
        include: \*
feign:
  hystrix:
    enabled: true