spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:7990
  application:
    name: base-mongodb
  data:
    mongodb:
      host: 120.79.91.131
      port: 27017
      username: gms_file_admin
      password: gms_file_admin
      database: gms_file
server:
  port: 8020