spring:
  profiles:
    active: @package.environment@
  application:
    name: base-mongodb
server:
  port: 8020
hystrix:
  command:
    helloService:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000