server:
  port: 8010
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: base-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'

zuul:
  routes:
    #拦截所有请求
    #      api: /**
    uaa:
      path: /uaa/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: auth2.0-center
security:
  oauth2:
    resource:
      user-info-uri:  http://uaa/user
      prefer-token-info: false
      loadBalanced: true