server:
  port: 8000
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: base-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9443/eureka  #注册 中心已经开启认证
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
zuul:
  routes:
#拦截所有请求
      api: /**