server:
  port: 8010
  tomcat:
    uri-encoding: UTF-8
spring:
  redis:
    host: 39.108.127.174
    port: 6379
    database: 1
    password: Dyny0763Redis
  application:
    name: base-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:7990
management:
  endpoints:
    web:
      exposure:
        include: '*'
zuul:
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时
  routes:
          api: /**