server:
  port: 8310 #8181
spring:
  profiles:
    active: @package.environment@
  main:
    allow-bean-definition-overriding: true
  application:
    name: mid-user
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:7990
management:
  endpoints:
    web:
      exposure:
        include: \*
feign:
  hystrix:
    enabled: true