server:
  port: 8340 #8181
spring:
  application:
    name: mid-region
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:7990
management:
  endpoints:
    web:
      exposure:
        include: \*