server:
  port: 8005
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: base-auth
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://193.112.68.193:3306/gms_auth
      username: root
      password: Paladin123
      initial-size: 1
      min-idle: 5
      max-active: 50
      max-wait: 6000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: select 1
      test-while-idle: false
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall,slf4j
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka  #注册 中心已经开启认证
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}