server:
  port: 8150 #8181
spring:
  application:
    name: service-generator
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka  #注册 中心已经开启认证
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
