server:
  port: 8010
  tomcat:
    uri-encoding: UTF-8
spring:
  cloud:
    gateway:
      routes:
        - predicates:
            - Path=/java/**
          filters:
            - StripPrefix=1
          uri: "http://localhost:8090/helloWorld"
  profiles:
    active: @package.environment@
  application:
    name: base-gateway
management:
  endpoints:
    web:
      exposure:
        include: '*'
#zuul:
#  sensitive-headers: Access-Control-Allow-Origin
#  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
#  host:
#    connect-timeout-millis: 1500000 #HTTP连接超时要比Hystrix的大
#    socket-timeout-millis: 600000   #socket超时
#  routes:
#          api: /**
hystrix:
  command:
    default:
      execution:
      timeout:
      enabled: true
      isolation:
      thread:
      timeoutInMilliseconds: 600000
ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 600000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1