server:
  profiles:
    active: @package.environment@
  port: 8015 #8181
spring:
  redis:
    host: 39.108.127.174
    port: 6379
    database: 1
    password: Dyny0763Redis
  cloud:
    nacos:
      discovery:
        server-addr: 47.107.72.98:7990
  application:
    name: base-redis
management:
  endpoints:
    web:
      exposure:
        include: \*
