server:
  port: 8100 #8181
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://120.79.91.131:3306/gms_cloud
      username: nacos_admin
      password: nacos_admin
      initial-size: 1
      min-idle: 5
      max-active: 50
      max-wait: 6000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: select 1
      test-while-idle: false
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall,slf4j
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  application:
    name: service-user
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  mvc:
    view:
      suffix: .html
      prefix: classpath:/templates/
management:
  endpoints:
    web:
      exposure:
        include: \*
