server:
  port: 8350 #8181
spring:
  application:
    name: mid-connector-v2
  cloud:
    nacos
    nacos:
      discovery:
        server-addr: 127.0.0.1:7990
management:
  endpoints:
    web:
      exposure:
        include: \*
feign:
  hystrix:
    enabled: true